### ISSUE TITLE
undefined method `permit' for "present":String

### ISSUE THREAD

**Issue by monucaapps** [letired/eduassist#134]
On submit, after select students attendances, gives this error:

NoMethodError at /school_classes/1/attendances
undefined method `permit' for "present":String
Did you mean?  print
line: 66

```ruby on rails
64 
65    def attendance_params(my_params)
66      my_params.permit(:present, :student_id)
67    end
68
```

**Comment by wabi69sabi** [comment]
...wrong params being passed...otherwise we would need some context here
